### ISSUE TITLE
Edits to layout object CSS not being honored?

### ISSUE THREAD

**Issue by ColinLondon** [DanShockley/FmClipTools#13]
I copy an object in FM. I use FmClipTools to convert it as XML. I then make my changes to CSS in a code editor and copy all. I then use FmClipTools convert the clipboard XML to FM object.
But when I paste ctrl+V in layout mode the edits I made are lost.

**Comment by DanShockley** [comment]
Interesting. Are you sure the edits you are making to the CSS are supported by FileMaker? It may be throwing away CSS that doesn't exactly fit its own format. 
A way to check this would be: after you have converted your XML to FM Objects, run the FmClipTools to convert back to XML. Then, paste into your XML editor. Does it include your edits? If so, then it sounds like FileMaker is rejecting your customized CSS. 
I haven't played around with editing the CSS in layout objects before, but just tried it. I was able to change a field with a light gray background to a field with dark gray background. Interestingly, I did that by only editing the info in the "LocalCSS" tag, not the FullCSS. So, my modified object had the old (light gray) info in FullCSS, but pasting it ignored the FullCSS and honored my edits in LocalCSS. 
Perhaps you are editing the FullCSS tag? 
Let me know more about what you are seeing.

**Comment by ColinLondon** [comment]
Hi ya, Dan. Interestingly, whether I copy a default object or one with a named style, I am not seeing the LocalCSS tag (just FullCSS). All very strange! Take care.

**Comment by DanShockley** [comment]
If the object you are copying has no modifications from its chosen theme style, I think it will not get a LocalCSS tag, since there isn't anything "local" to the object. So, I think what you are seeing makes sense. 
But, note that it always copies the FullCSS, which includes the styling set in the object style of the theme, since the XML in the clipboard should be verbose about the object (see below). Then, when paste-target layout uses the same theme as the copied object, FileMaker ignores the FullCSS when pasting (as far as I can tell), since the only thing it needs to process during the paste are the "tweaks" (modifications) that pasted object has when compared the unmodified style. 
I believe, however, that if you then pasted the object onto a layout with a _different_ theme, whether FileMaker might _honor_ the FullCSS, since the object is NOT using a style of the layout's theme, so to retain its style, the pasting process needs to get all the details stored in FullCSS. I think that describes how FileMaker behaves with copy/paste, and that's the only way I could see it being able to paste the object as it was when copied, if pasted onto a layout with a different theme. Thus, the copy needs to be verbose in storing the FullCSS.

**Comment by DanShockley** [comment]
I'll close this for now - reopen or post another Issue if you think there is more to discuss.
