### ISSUE TITLE
`fmClip - Escape text for use as FM Calc.applescript` 

### ISSUE THREAD

**Issue by ericgarig** [DanShockley/FmClipTools#5]
instead of having `makeEscapedMoreLegible` property,  it might be easier to convert the escaped text block into a FileMaker list where each item is a string of the text block

**Comment by DanShockley** [comment]
Doing that would, I believe, create the same issue as the makeEscapedMoreLegible option: when you convert back, each line would end up with a leading space character. So, you'd still want the default to be NOT adding an extra Char13. Using the List function is just an alternate way of adding a Char13 to each line, so it would have the same negative affect on reversibility (lost fidelity to the original).

**Comment by DanShockley** [comment]
This issue brought up a good point: making the output more legible is a good goal, but the current method was flawed, since it broke fidelity after double-conversion. 
Instead, it now breaks the output into concatenated FileMaker strings, which improves legibility and yet still, when evaluated back into the original, retains full fidelity, producing the original text. So, that flag is now the DEFAULT action, as of this change in version 1.4 of this script.
